name: Oman_Paleogeography
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - blas
  - bleach
  - bottleneck
  - branca
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - et_xmlfile
  - executing
  - folium
  - fonttools
  - freetype
  - geos
  - h11
  - httpcore
  - httpx
  - idna
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openpyxl
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pillow
  - pip
  - platformdirs
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scipy
  - send2trash
  - setuptools
  - shapely
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
      - mplstereonet==0.6.3
      - patsy==1.0.1
      - radage==0.1.0
      - statsmodels==0.14.4
      - pmagpy